# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            'Hyungjoo Cha'
<<<<<<< HEAD
tagline:          'Hyungjoo Cha'
description:      '-'
=======
tagline:          '-'
description:      '--'
>>>>>>> 07d790963344fff1aa352e6b9ea78afca96c6461
url:              "https://hjcha.github.io"
baseurl:          ""

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
